import { Copy, Check, Download, File as FileIcon, Folder, Terminal } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState, useEffect, useRef } from 'react'

interface CopyButtonProps {
  text: string
}

function CopyButton({ text }: CopyButtonProps) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button
      onClick={handleCopy}
      className="rounded p-1.5 transition-colors hover:bg-white/10 cursor-pointer"
    >
      {copied ? (
        <Check className="h-4 w-4 text-green-500" />
      ) : (
        <Copy className="h-4 w-4 text-zinc-400" />
      )}
    </button>
  )
}

export function Installation() {
  const [selectedFile, setSelectedFile] = useState<'Dockerfile.worker' | 'docker-compose.yml' | '.env' | 'mcp.config.json' | 'README.md'>('README.md')

  const [consoleLogs, setConsoleLogs] = useState<string[]>([])
  const [isConsoleRunning, setIsConsoleRunning] = useState(false)
  const consoleEndRef = useRef<HTMLDivElement>(null)
  const hasStartedConsole = useRef(false)

  const fileContents = {
    'Dockerfile.worker': `ARG BASE_VERSION=2.0.0
FROM buremba/peerbot-worker-base:\${BASE_VERSION}

# === CUSTOMIZE BELOW THIS LINE ===
# This Dockerfile extends the peerbot worker base image with your custom tools and dependencies.
# The same Dockerfile works for local Docker development.

# Example: Add system packages
# RUN apt-get update && apt-get install -y \\
#     postgresql-client \\
#     && rm -rf /var/lib/apt/lists/*

# Example: Add Python packages
# RUN pip install --no-cache-dir \\
#     pandas \\
#     matplotlib \\
#     requests

# Example: Add Node.js packages
# RUN bun add @octokit/rest lodash

# Example: Copy custom scripts
# COPY ./scripts /workspace/scripts
# RUN chmod +x /workspace/scripts/*.sh

# Example: Set custom environment variables
# ENV MY_CUSTOM_VAR=value

# Example: Install language runtimes
# RUN curl -fsSL https://deno.land/install.sh | sh`,
    'docker-compose.yml': `# Generated by @peerbot/cli
# You can modify this file as needed

name: my-peerbot

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - my-peerbot-network

  gateway:
    image: buremba/peerbot-gateway:2.0.0
    ports:
      - "8080:8080"
    environment:
      DEPLOYMENT_MODE: docker
      WORKER_IMAGE: my-peerbot-worker:latest
      QUEUE_URL: redis://redis:6379/0
      SLACK_BOT_TOKEN: \${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: \${SLACK_APP_TOKEN}
      SLACK_SIGNING_SECRET: \${SLACK_SIGNING_SECRET}
      PUBLIC_GATEWAY_URL: \${PUBLIC_GATEWAY_URL:-}
      NODE_ENV: \${NODE_ENV:-development}
      MCP_CONFIG_URL: file:///app/.peerbot/mcp.config.json
      ENCRYPTION_KEY: \${ENCRYPTION_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces:/app/workspaces
      - env_storage:/app/.peerbot/env
      - ./.peerbot:/app/.peerbot:ro
    networks:
      - my-peerbot-network
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.worker
      args:
        BASE_VERSION: 2.0.0
        NODE_ENV: \${NODE_ENV:-development}
    image: my-peerbot-worker:latest
    command: echo "Worker image built successfully"
    profiles:
      - build-only

networks:
  my-peerbot-network:
    driver: bridge

volumes:
  redis_data:
  env_storage:`,
    '.env': `# Slack Configuration
SLACK_SIGNING_SECRET=your_slack_signing_secret_here
SLACK_BOT_TOKEN=xoxb-your_slack_bot_token_here
SLACK_APP_TOKEN=xapp-your_slack_app_token_here

# Anthropic Configuration
ANTHROPIC_API_KEY=your_anthropic_api_key_here

# Gateway Configuration
PUBLIC_GATEWAY_URL=http://localhost:8080/

# Security
ENCRYPTION_KEY={{ENCRYPTION_KEY}}

# CLI Version (used for image tags)
CLI_VERSION=2.0.0

# MCP Server Credentials
# Add your OAuth client secrets and API keys below:
# GITHUB_CLIENT_ID=your_github_client_id_here
# GITHUB_CLIENT_SECRET=your_github_client_secret_here`,
    'mcp.config.json': `{
  "mcpServers": {
    "github": {
      "url": "https://api.githubcopilot.com/mcp/",
      "oauth": {
        "authUrl": "https://github.com/login/oauth/authorize",
        "tokenUrl": "https://github.com/login/oauth/access_token",
        "clientId": "\${GITHUB_CLIENT_ID}",
        "clientSecret": "\${env:GITHUB_CLIENT_SECRET}",
        "scopes": [
          "repo",
          "read:user"
        ],
        "grantType": "authorization_code",
        "responseType": "code"
      }
    },
    "sentry": {
      "url": "https://mcp.sentry.dev/mcp"
    }
  }
}`,
    'README.md': `# my-peerbot

Here is an example of Peerbot with a custom Dockerfile and MCP support.

## Quick Start

\`\`\`bash
# Start the services
docker compose up -d

# View logs
docker compose logs -f

# Stop the services
docker compose down
\`\`\`

## Configuration

### Environment Variables

Edit \`.env\` to configure:
- \`SLACK_BOT_TOKEN\` - Your Slack bot token
- \`SLACK_APP_TOKEN\` - Your Slack app token
- \`SLACK_SIGNING_SECRET\` - Your Slack signing secret
- \`ANTHROPIC_API_KEY\` - Your Anthropic API key (optional if users provide their own)
- \`PUBLIC_GATEWAY_URL\` - Public URL for OAuth callbacks

### Worker Customization

Edit \`Dockerfile.worker\` to add custom tools and dependencies.

Example customizations:
\`\`\`dockerfile
# Add system packages
RUN apt-get update && apt-get install -y postgresql-client

# Add Python packages
RUN pip install pandas matplotlib

# Add Node.js packages
RUN bun add @octokit/rest
\`\`\`

When you modify \`Dockerfile.worker\` or context files, rebuild the worker image:
\`\`\`bash
docker compose build worker
\`\`\`

The gateway will automatically pick up the latest worker image.

## Services

The docker-compose.yml defines these services:
- **redis** - Redis cache and queue
- **gateway** - Slack integration and worker orchestration
- **worker** - Claude worker (build-only, spawned dynamically)

## Learn More

- [Peerbot Documentation](https://github.com/buremba/peerbot)
- [CLI Reference](https://github.com/buremba/peerbot/tree/main/packages/cli)
- [Examples](https://github.com/buremba/peerbot/tree/main/examples)

## Support

- [GitHub Issues](https://github.com/buremba/peerbot/issues)`
  }

  useEffect(() => {
    // Prevent multiple executions
    if (hasStartedConsole.current) return
    
    const logs = [
      "$ docker compose up",
      "[+] Building 0.1s (10/10) FINISHED",
      "[+] Running 3/3",
      "✔ Container redis  Healthy",
      "✔ Container gateway  Started",
      "✔ Container worker  Built",
      "ℹ️  Starting Peerbot services...",
      "✅ MCP servers initialized",
      "✅ Docker daemon is connected with gVisor sandbox",
      "🚀 Peerbot is now running in Socket mode powering your bot"
    ]

    const delays = [0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]

    hasStartedConsole.current = true
    setIsConsoleRunning(true)
    setConsoleLogs([])

    logs.forEach((log, index) => {
      setTimeout(() => {
        setConsoleLogs((prev: string[]) => [...prev, log])
        if (index === logs.length - 1) {
          setTimeout(() => setIsConsoleRunning(false), 500)
        }
      }, delays[index])
    })
  }, [])

  useEffect(() => {
    if (consoleEndRef.current) {
      consoleEndRef.current.scrollIntoView({ behavior: "smooth" })
    }
  }, [consoleLogs])

  return (
    <section id="install" className="p-8">
      <div className="mx-auto max-w-7xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="mb-16 text-center"
        >
          <div className="mb-4 flex items-center justify-center gap-3">
            <h2 className="text-4xl font-bold text-zinc-100">
              Installation
            </h2>
          </div>
          <p className="text-xl text-zinc-400">
            Get started with PeerBot in seconds
          </p>
        </motion.div>

        <div className="mx-auto max-w-4xl space-y-12">
          {/* Installation Command */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            viewport={{ once: true }}
            className="text-center"
          >
      
            
            <div className="relative inline-block">
              <div className="absolute inset-0 bg-gradient-to-r from-pink-500/20 to-purple-500/20 rounded-lg blur-xl" />
              <div className="relative border-2 border-zinc-700 rounded-lg bg-zinc-900/50 backdrop-blur-sm p-1">
                <div className="flex items-center gap-3 bg-zinc-800/50 rounded-md px-4 py-3">
                  <code className="text-lg font-mono text-zinc-100">npm create peerbot</code>
                  <CopyButton text="npm create peerbot" />
                </div>
              </div>
            </div>
          </motion.div>

          {/* VSCode-style Editor */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            viewport={{ once: true }}
          >
            <div className="border border-zinc-800 rounded-lg overflow-hidden shadow-2xl">
              {/* Title Bar */}
              <div className="bg-zinc-800 border-b border-zinc-700 px-4 py-2 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-red-500" />
                  <div className="h-3 w-3 rounded-full bg-yellow-500" />
                  <div className="h-3 w-3 rounded-full bg-green-500" />
                </div>
                <div className="text-xs text-zinc-400 font-mono">my-peerbot-project</div>
                <div className="w-16" />
              </div>

              <div className="flex h-[450px]">
                {/* Sidebar */}
                <div className="w-48 bg-zinc-900 border-r border-zinc-700 p-3 flex-shrink-0">
                  <div className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-3">
                    Explorer
                  </div>
                  <div className="space-y-1">
                    <div className="flex items-center gap-2 text-xs text-zinc-300 font-medium">
                      <Folder className="w-3 h-3 text-blue-400" />
                      my-peerbot-project
                    </div>
                    <div className="ml-4 space-y-0.5">
                      {['Dockerfile.worker', 'docker-compose.yml', '.env', 'mcp.config.json', 'README.md'].map((fileName) => (
                        <button
                          key={fileName}
                          onClick={() => setSelectedFile(fileName as any)}
                          className={`w-full flex items-center gap-1.5 px-1.5 py-0.5 rounded text-xs transition-colors cursor-pointer ${
                            selectedFile === fileName
                              ? 'bg-zinc-700 text-zinc-100'
                              : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800'
                          }`}
                        >
                          <FileIcon className="w-3 h-3" />
                          {fileName}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Main content area - editor with terminal at bottom */}
                <div className="flex-1 bg-zinc-950 flex flex-col overflow-hidden">
                  {/* Editor */}
                  <div className="flex-1 flex flex-col min-h-0">
                    {selectedFile ? (
                      <>
                        {/* Tab */}
                        <div className="bg-zinc-900 border-b border-zinc-700 px-4 py-2 flex items-center gap-2 flex-shrink-0">
                          <FileIcon className="w-3 h-3 text-zinc-400" />
                          <span className="text-sm text-zinc-200">{selectedFile}</span>
                        </div>
                        
                        {/* Content */}
                        <div className="flex-1 p-4 overflow-y-scroll overflow-x-hidden min-h-0 max-h-full">
                          <pre className="text-sm text-zinc-300 font-mono whitespace-pre-wrap">
                            {fileContents[selectedFile as keyof typeof fileContents]}
                          </pre>
                        </div>
                      </>
                    ) : (
                      <div className="flex-1 flex items-center justify-center text-zinc-500 text-sm">
                        Select a file to view its contents
                      </div>
                    )}
                  </div>

                  {/* Console/Terminal at bottom */}
                  <div className="h-36 bg-black/95 border-t border-zinc-700 flex flex-col flex-shrink-0">
                    {/* Console Header */}
                    <div className="bg-zinc-900 border-b border-zinc-700 px-4 py-1.5 flex items-center justify-between">
                     
                      <div className="flex items-center gap-1 text-xs text-zinc-400 font-mono">
                        <Terminal className="w-3 h-3" />
                        $ docker compose up
                      </div>
                      <div className="w-16" />
                    </div>

                    {/* Console Content */}
                    <div className="flex-1 p-3 overflow-auto">
                      <div className="space-y-0.5">
                        {consoleLogs.length === 0 ? (
                          <div className="text-zinc-500 text-xs font-mono animate-pulse">
                            $ docker compose up
                          </div>
                        ) : (
                          consoleLogs.map((log, index) => (
                            <div
                              key={index}
                              className="text-xs font-mono text-zinc-300 animate-fade-in"
                              style={{ animationDelay: `${index * 0.05}s` }}
                            >
                              {log.startsWith("$") ? (
                                <span className="text-green-400">{log}</span>
                              ) : log.includes("✔") ? (
                                <span className="text-green-300">{log}</span>
                              ) : log.includes("✅") ? (
                                <span className="text-green-400">{log}</span>
                              ) : log.includes("🚀") ? (
                                <span className="text-yellow-400 font-semibold">{log}</span>
                              ) : log.includes("ℹ️") ? (
                                <span className="text-blue-400">{log}</span>
                              ) : (
                                <span>{log}</span>
                              )}
                            </div>
                          ))
                        )}
                        {isConsoleRunning && (
                          <div className="text-xs font-mono text-green-400 animate-pulse">
                            █
                          </div>
                        )}
                      </div>
                      <div ref={consoleEndRef} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}